apiVersion: v1
kind: Template
metadata:
  name: ldap
labels:
  app.kubernetes.io/instance: ace-mq-tls-example-ldap
  project: ace-mq-tls-example
objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: bootstrap.ldif
    binaryData:
      bootstrap.ldif: ${BOOTSTRAP_LDIF}
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: ldap
      labels:
        app: ldap
    spec:
      selector:
        matchLabels:
          app: ldap
      template:
        metadata:
          labels:
            app: ldap
        spec:
          containers:
            - name: ldap
              image: docker.io/mashrurmia/bitnami-openldap
              imagePullPolicy: Always
              ports:
              - name: ldap-port
                containerPort: 1389
              env:
              - name: LDAP_ADMIN_USERNAME
                value: admin
              - name: LDAP_ADMIN_PASSWORD
                value: admin
              - name: LDAP_ROOT
                value: dc=ibm,dc=com
              volumeMounts:
              - name: ldif
                mountPath: /ldifs
                readOnly: true
          volumes:
          - name: ldif
            configMap:
              name: bootstrap.ldif
  - kind: Service
    apiVersion: v1
    metadata:
      name: ldap
      matchLabels:
        app: ldap
    spec:
      selector:
        app: ldap
      type: NodePort
      ports:
      - name: ldap-port
        protocol: TCP
        port: 1389
        targetPort: ldap-port
parameters:
  - name: BOOTSTRAP_LDIF
